package org.ruru.ffta2editor.model.ability;

public class AbilityId {
    
    public short id;
    public String name;

    public AbilityId(short id, String name) {
        this.id = id;
        this.name = name;
    }

    public String toString() {
        return name;
    }

    // public String toString() {
    //     return abilityNames[id];
    // }

    public static int[] vanillaAbilityHelp = {
        0,
        103,
        103,
        103,
        116,
        61,
        48,
        21,
        7,
        46,
        244,
        52,
        11,
        27,
        146,
        3,
        66,
        105,
        117,
        66,
        66,
        66,
        66,
        111,
        58,
        47,
        19,
        4,
        45,
        152,
        49,
        8,
        26,
        143,
        2,
        103,
        87,
        114,
        103,
        103,
        141,
        233,
        111,
        153,
        86,
        28,
        129,
        119,
        134,
        128,
        128,
        128,
        128,
        122,
        133,
        210,
        210,
        210,
        146,
        207,
        305,
        206,
        272,
        187,
        187,
        187,
        236,
        236,
        236,
        239,
        239,
        239,
        269,
        25,
        24,
        17,
        124,
        165,
        118,
        8,
        106,
        276,
        101,
        156,
        208,
        208,
        215,
        151,
        90,
        307,
        248,
        165,
        308,
        309,
        225,
        192,
        225,
        78,
        74,
        191,
        238,
        240,
        179,
        63,
        223,
        74,
        191,
        220,
        68,
        203,
        145,
        33,
        187,
        236,
        239,
        208,
        66,
        201,
        218,
        225,
        111,
        103,
        211,
        53,
        76,
        137,
        145,
        219,
        277,
        62,
        9,
        145,
        2,
        94,
        42,
        291,
        218,
        168,
        271,
        270,
        309,
        274,
        135,
        301,
        84,
        290,
        278,
        279,
        116,
        157,
        96,
        118,
        64,
        307,
        323,
        293,
        48,
        124,
        145,
        248,
        109,
        275,
        187,
        236,
        239,
        280,
        76,
        90,
        94,
        224,
        273,
        281,
        39,
        102,
        187,
        236,
        239,
        278,
        310,
        324,
        320,
        77,
        208,
        132,
        293,
        232,
        145,
        208,
        31,
        201,
        225,
        45,
        297,
        148,
        153,
        111,
        300,
        19,
        111,
        32,
        175,
        228,
        229,
        230,
        231,
        282,
        196,
        103,
        116,
        28,
        4,
        49,
        25,
        17,
        320,
        311,
        402,
        32,
        142,
        16,
        38,
        15,
        150,
        60,
        268,
        66,
        66,
        49,
        4,
        47,
        109,
        113,
        65,
        64,
        186,
        173,
        185,
        8,
        321,
        272,
        66,
        79,
        278,
        298,
        66,
        218,
        239,
        236,
        175,
        151,
        149,
        70,
        66,
        58,
        66,
        406,
        407,
        110,
        118,
        121,
        121,
        121,
        121,
        121,
        121,
        121,
        121,
        121,
        121,
        121,
        169,
        169,
        169,
        169,
        169,
        169,
        169,
        169,
        169,
        169,
        169,
        169,
        169,
        169,
        169,
        169,
        169,
        169,
        169,
        169,
        169,
        79,
        153,
        42,
        165,
        307,
        111,
        321,
        308,
        30,
        13,
        164,
        125,
        2,
        53,
        189,
        222,
        193,
        226,
        178,
        221,
        202,
        237,
        235,
        79,
        67,
        80,
        70,
        76,
        74,
        73,
        77,
        213,
        187,
        236,
        239,
        35,
        38,
        208,
        212,
        15,
        174,
        12,
        56,
        16,
        45,
        278,
        310,
        79,
        42,
        22,
        59,
        232,
        224,
        134,
        53,
        288,
        267,
        17,
        321,
        4,
        172,
        28,
        90,
        276,
        308,
        248,
        148,
        293,
        217,
        278,
        187,
        236,
        239,
        76,
        71,
        68,
        72,
        69,
        223,
        15,
        190,
        40,
        73,
        142,
        312,
        32,
        145,
        49,
        8,
        103,
        42,
        53,
        31,
        103,
        146,
        187,
        309,
        66,
        116,
        167,
        31,
        197,
        106,
        37,
        36,
        116,
        171,
        313,
        96,
        145,
        299,
        90,
        323,
        88,
        130,
        98,
        83,
        100,
        20,
        115,
        18,
        108,
        120,
        22,
        23,
        183,
        184,
        214,
        68,
        166,
        135,
        92,
        109,
        205,
        134,
        82,
        97,
        93,
        99,
        89,
        81,
        225,
        163,
        227,
        131,
        140,
        118,
        314,
        95,
        315,
        307,
        321,
        187,
        204,
        242,
        182,
        66,
        70,
        74,
        73,
        292,
        118,
        160,
        316,
        162,
        134,
        130,
        296,
        66,
        310,
        143,
        16,
        111,
        141,
        233,
        109,
        123,
        22,
        35,
        166,
        234,
        149,
        116,
        106,
        70,
        75,
        321,
        76,
        104,
        320,
        17,
        35,
        325,
        317,
        139,
        249,
        110,
        144,
        294,
        250,
        251,
        199,
        200,
        127,
        252,
        136,
        253,
        111,
        322,
        109,
        103,
        211,
        66,
        216,
        45,
        53,
        50,
        43,
        317,
        64,
        44,
        75,
        76,
        161,
        66,
        241,
        188,
        176,
        137,
        17,
        32,
        66,
        145,
        112,
        322,
        74,
        219,
        57,
        195,
        266,
        70,
        89,
        218,
        277,
        62,
        74,
        307,
        218,
        217,
        286,
        10,
        145,
        155,
        138,
        6,
        272,
        17,
        107,
        55,
        90,
        79,
        165,
        90,
        89,
        28,
        45,
        287,
        289,
        66,
        85,
        142,
        103,
        146,
        187,
        309,
        66,
        116,
        167,
        31,
        2,
        147,
        301,
        17,
        5,
        94,
        187,
        243,
        79,
        109,
        8,
        181,
        177,
        303,
        42,
        33,
        54,
        26,
        109,
        72,
        94,
        79,
        291,
        45,
        40,
        154,
        34,
        404,
        318,
        319,
        283,
        284,
        159,
        218,
        317,
        269,
        218,
        306,
        198,
        93,
        91,
        1,
        284,
        0,
        187,
        239,
        236,
        168,
        271,
        270,
        405,
        56,
        41,
        103,
        236,
        103,
        161,
        90,
        295,
        74,
        66,
        304,
        51,
        265,
        170,
        90,
        302,
        66,
        66,
        321,
        110,
        145,
        40,
        66,
        168,
        175,
        175,
        175,
        62,
        254,
        255,
        256,
        257,
        258,
        259,
        260,
        180,
        261,
        262,
        263,
        209,
        264,
        265,
        266,
        267,
        268,
        269,
        270,
        271,
        272,
        273,
        274,
        275,
        276,
        277,
        278,
        279,
        280,
        281,
        282,
        283,
        284,
        285,
        286,
        287,
        288,
        289,
        290,
        291,
        292,
        293,
        294,
        295,
        296,
        297,
        298,
        299,
        300,
        301,
        302,
        303,
        304,
        305,
        306,
        307,
        308,
        309,
        310,
        311,
        312,
        313,
        314,
        315,
        316,
        317,
        318,
        319,
        320,
        321,
        322,
        323,
        324,
        325,
        326,
        327,
        328,
        329,
        330,
        331,
        332,
        333,
        334,
        335,
        336,
        337,
        338,
        339,
        340,
        341,
        342,
        343,
        344,
        345,
        346,
        347,
        348,
        349,
        350,
        351,
        352,
        353,
        354,
        355,
        356,
        357,
        358,
        359,
        360,
        361,
        362,
        363,
        364,
        365,
        366,
        367,
        368,
        369,
        370,
        371,
        372,
        373,
        374,
        375,
        376,
        377,
        378,
        379,
        380,
        381,
        382,
        383,
        384,
        385,
        386,
        387,
        388,
        389,
        390,
        391,
        392,
        393,
        394,
        395,
        396,
        397,
        398,
        399,
        400,
        401,
        285,
        8,
        53,
        40,
        283,
        300,
        66,
        66,
        66,
        66,
        64,
        66,
        403,
        66,
        126,
        103,
        66,
        194,
        0,
        0,
        0,
        0,
        0,
    };

    public static String[] abilityNames = {
        "",
        "Potion",
        "Hi-Potion",
        "X-Potion",
        "Ether",
        "Elixir",
        "Phoenix Down",
        "Echo Grass",
        "Maiden's Kiss",
        "Gold Needle",
        "Holy Water",
        "Antidote",
        "Eye Drops",
        "Bandage",
        "Remedy",
        "Handkerchief",
        "Knot of Rust",
        "Eureka Crystal",
        "Grimoire Stone",
        "Dark Matter",
        "Mirror Potion",
        "Mirror Hi-Potion",
        "Mirror X-Potion",
        "Mirror Ether",
        "Mirror Elixir",
        "Mirror Down",
        "Mirror Echo",
        "Mirror Kiss",
        "Mirror Needle",
        "Mirror Water",
        "Mirror Antidote",
        "Mirror Drops",
        "Mirror Bandage",
        "Mirror Remedy",
        "Mirror Kerchief",
        "Mirror Rust",
        "Mirror Crystal",
        "Mirror Grimoire",
        "Mirror Matter",
        "First Aid",
        "Rend Power",
        "Rend Magick",
        "Rend MP",
        "Rend Speed",
        "Mug Gil",
        "Provoke",
        "Gauge",
        "Steal Items",
        "Steal Gil",
        "Loot Lv. 1",
        "Loot Lv. 2",
        "Loot Lv. 3",
        "Loot Lv. 4",
        "Steal Accessory",
        "Steal Limelight",
        "Cure",
        "Cura",
        "Curaga",
        "Esuna",
        "Raise",
        "Arise",
        "Reraise",
        "Refresh",
        "Fire",
        "Fira",
        "Firaga",
        "Thunder",
        "Thundara",
        "Thundaga",
        "Blizzard",
        "Blizzara",
        "Blizzaga",
        "Focus",
        "Leg Shot",
        "Arm Shot",
        "Cupid",
        "Burial",
        "Take Aim",
        "Lightning Strike",
        "Blackout",
        "Nurse",
        "Defend",
        "Cover",
        "Parley",
        "Saint Cross",
        "Holy Blade",
        "Sanctify",
        "War Cry",
        "Rush",
        "Wild Swing",
        "Beat Down",
        "Blitz",
        "Air Render",
        "Aurablast",
        "Air Blast",
        "Back Draft",
        "Wind Slash",
        "Iai Blow",
        "Blade Bash",
        "Shimmering Blade",
        "Skyfury Blade",
        "Hoarfrost Blade",
        "Lifethread Blade",
        "Unburden Soul",
        "Throw",
        "Wood Veil",
        "Fire Veil",
        "Earth Veil",
        "Gold Veil",
        "Water Veil",
        "Unspell",
        "Oblivion",
        "Prominence",
        "Tempest",
        "Freezeblink",
        "Star Cross",
        "Stardust",
        "Deluge",
        "Rockfall",
        "Wild Tornado",
        "Magick Hammer",
        "White Wind",
        "Angel Whisper",
        "Night",
        "Screech",
        "War Dance",
        "Roar",
        "Sandstorm",
        "Cornered",
        "Matra Magick",
        "Bad Breath",
        "Eerie Sound Wave",
        "Unction",
        "Self-destruct",
        "Doom",
        "Roulette",
        "Quake",
        "Expose Weakness",
        "Mighty Guard",
        "Dragon Force",
        "Sonic Boom",
        "Oust",
        "Advice",
        "Vitals Shot",
        "Hunting",
        "Counter Force",
        "Ultima Shot",
        "Sidewinder",
        "Recharge",
        "Magick Frenzy",
        "Body Slam",
        "Greased Lightning",
        "Lifetap",
        "Roundhouse",
        "Earth Render",
        "Chakra",
        "Revive",
        "Exorcise",
        "Holy Sign",
        "Jump",
        "Lancet",
        "Wyrmtamer",
        "Fire Breath",
        "Thunder Breath",
        "Ice Breath",
        "Wyrmkiller",
        "Bangaa Cry",
        "Whirl Burst",
        "Meltdown",
        "Rend Weapon",
        "Hibernate",
        "Mow Down",
        "Aura",
        "Bulwark",
        "Fire Soul",
        "Thunder Assault",
        "Blizzard Tackle",
        "Ultima Sword",
        "Pummel",
        "Dark Fist",
        "Withering Strike",
        "Lifebane",
        "Holy Strike",
        "Cross-counter",
        "Inner Focus",
        "Rend Armor",
        "Dispel",
        "Holy",
        "Barrier",
        "Water",
        "Aero",
        "Break",
        "Pilfer",
        "Astra",
        "Piercing Cry",
        "Rasp",
        "Discipline",
        "Silence",
        "Soul Sphere",
        "Haste",
        "Lifebreak",
        "Prime",
        "Foresight",
        "Buckshot",
        "Scope",
        "Mortar",
        "Target",
        "Potion Shell",
        "Ether Shell",
        "Snigger",
        "Suggestion",
        "Hypochondria",
        "Shadow of Doubt",
        "Charisma",
        "Agitate",
        "Traumatize",
        "Mug",
        "Hastega",
        "Quicken",
        "Slow",
        "Reflect",
        "Stop",
        "Extend",
        "Undo",
        "Transmute",
        "Protometeor",
        "Flare",
        "Poison",
        "Toad",
        "Death",
        "Drain",
        "Syphon",
        "Gravity",
        "Graviga",
        "Lv. 3 Dark",
        "Lv. 5 Haste",
        "Lv. ? Shadowflare",
        "Blind",
        "Scathe",
        "Esunaga",
        "Gigaflare",
        "Bio",
        "Ultima Blow",
        "Study",
        "Natural Selection",
        "Earth Dragon Tome",
        "Rime Bolt Tome",
        "Thunder Flare Tome",
        "Shadow Shade Tome",
        "Force",
        "Mad Scientist",
        "Gold Hourglass",
        "Otherworldly Wind",
        "Dark Elixir",
        "Shadowflare",
        "Soul Spring",
        "Light Curtain",
        "Veil of Darkness",
        "Flash Bomb",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "Baknamy",
        "Sprite",
        "Lamia",
        "Wolf",
        "Dreamhare",
        "Werewolf",
        "Antlion",
        "Shelling",
        "Malboro",
        "Deadly Nightshade",
        "Cockatrice",
        "Flan",
        "Bomb",
        "Zombie",
        "Ghost",
        "Deathscythe",
        "Floating Eye",
        "Ahriman",
        "Headless",
        "Behemoth",
        "Drake",
        "Swarmstrike",
        "Shadowstick",
        "Checkmate",
        "Featherblow",
        "Swallowtail",
        "Manastrike",
        "Piercing Blow",
        "Nighthawk",
        "Protect",
        "Shell",
        "Tranq",
        "Leap",
        "Oil",
        "Sleep",
        "Fire Whip",
        "Earth Heal",
        "White Flame",
        "Shining Air",
        "Evil Gaze",
        "Boulder Crush",
        "Sliprain",
        "Thunderous Roar",
        "Doublecast",
        "Poison Blade",
        "Oil Blade",
        "Sleep Blade",
        "Slow Blade",
        "Confusion Blade",
        "Stun Blade",
        "Maim Blade",
        "Doom Blade",
        "Unicorn",
        "Ifrit",
        "Ramuh",
        "Shiva",
        "Kirin",
        "Carbuncle",
        "Maduin",
        "Phoenix",
        "Shadowbind",
        "Last Breath",
        "Aphonia",
        "Nightmare",
        "Ague",
        "Rockseal",
        "Ultima Masher",
        "Doubleshot",
        "Beso Toxico",
        "Death Sickle",
        "Vanish",
        "Marksman's Spite",
        "Armor Shot",
        "Weapon Shot",
        "Wallet Shot",
        "Sheep Count",
        "100% Wool",
        "Cuisine",
        "Tail Wag",
        "Chocobo Rush",
        "Toadsong",
        "Friend",
        "Catnip",
        "Moogle Attack",
        "Moogle Guard",
        "Moogle Lance",
        "Moogle Rush",
        "Moogle Shield",
        "Moogle Aid",
        "Moogle Disarm",
        "Ultima Charge",
        "Fireshot",
        "Boltshot",
        "Iceshot",
        "Confushot",
        "Charmshot",
        "Blindshot",
        "Silenceshot",
        "Stopshot",
        "Weapon Toss",
        "Ring Toss",
        "Molotov Cocktail",
        "Ball Toss",
        "Dagger Toss",
        "Smile Toss",
        "Gil Toss",
        "Red Spring",
        "Blue Screw",
        "Green Gear",
        "Silver Disc",
        "Gold Battery",
        "Black Ingot",
        "Chroma Gem",
        "Gold Moogletron",
        "Choco Cure",
        "Choco Esuna",
        "Choco Flame",
        "Choco Meteor",
        "Choco Beak",
        "Choco Recharge",
        "Choco Guard",
        "Choco Barrier",
        "Prime",
        "Cure Cannon",
        "Protect Cannon",
        "Shell Cannon",
        "Ether Cannon",
        "Teleport Cannon",
        "Ether Boost",
        "Blowback",
        "Scream",
        "Hone Senses",
        "Furore",
        "Ground Shaker",
        "Smite of Rage",
        "Inner Calm",
        "Helm Smash",
        "Smash",
        "Sten Needle",
        "Silence Gas",
        "Leech",
        "Love Potion",
        "Life Bond",
        "Mirror Items",
        "Camouflage",
        "Awareness",
        "Souleater",
        "Sword of Darkness",
        "Sword of Light",
        "Haunting Vision",
        "Block!",
        "Strike!",
        "Charge!",
        "Razzle-dazzle",
        "Tsunami",
        "Pickpocket",
        "Strong-arm",
        "Pillage",
        "Power Crush",
        "Mind Crush",
        "Speed Crush",
        "Soul Crush",
        "Cyclone",
        "Shield Bash",
        "Whirlwind",
        "En Garde",
        "Battle Cry",
        "Overpower",
        "Tenacity",
        "Full Assault",
        "Sneak Attack",
        "Sweeping Spin",
        "Blast Wave",
        "Shining Flare",
        "Venom Squall",
        "Avalanche",
        "Mist Storm",
        "Nature's Embrace",
        "Artifice's Embrace",
        "Life's Embrace",
        "Earth's Embrace",
        "Trophy Hunt",
        "Shadow Stalk",
        "Salvage",
        "Life of Crime",
        "Steal",
        "Swipe",
        "Razor's Edge",
        "Flee",
        "Mincing Minuet",
        "Blade Dance",
        "Forbidden Dance",
        "Slow Dance",
        "Witch Hunt",
        "Polka",
        "Heathen Frolic",
        "Jitterbug",
        "Requiem",
        "Hide",
        "Angelsong",
        "Battle Chant",
        "Magickal Refrain",
        "Nameless Song",
        "Magick Ballad",
        "Soul Etude",
        "Wermut",
        "Nesiaam",
        "Lennart",
        "Hilo",
        "Elpe",
        "Viola",
        "Ljda",
        "Adelaide",
        "Abyssal Slash",
        "Time Blade",
        "Saber",
        "Dimensional Rift",
        "Annul",
        "Sheol",
        "Rebirth",
        "Escort",
        "Flourish",
        "Fawn",
        "Enchant",
        "Interrogate",
        "Succor",
        "Impassion",
        "Reckless Abandon",
        "Magick Hammer",
        "Goblin Attack",
        "Mutilate",
        "White Wind",
        "Angel Whisper",
        "Meteorite",
        "Lv. ? Holy",
        "Petrifying Rattle",
        "Night",
        "Poisonous Frog",
        "Kiss",
        "Hand Slap",
        "Twister",
        "Eternal Sleep",
        "Eternal Oblivion",
        "Screech",
        "Summon Pack",
        "Fangs",
        "Chilling Blow",
        "Fiery Blow",
        "Shadowy Blow",
        "War Dance",
        "Illude",
        "Go-Go Dance",
        "Hip Attack",
        "Roar",
        "Howl",
        "Slug",
        "Assault",
        "Sandstorm",
        "Cannibalize",
        "Suffocate",
        "Bile",
        "Mucus",
        "Saliva",
        "Subsidence",
        "Limit Glove",
        "Matra Magick",
        "Headbutt",
        "Sonic Spin",
        "Rain of Stone",
        "Munch",
        "Resonate",
        "Bad Breath",
        "Eerie Sound Wave",
        "Goo",
        "Malboro Song",
        "Putrid Breath",
        "Purify",
        "Honeyed Breath",
        "Love Song",
        "Cloying Breath",
        "Horn Blow",
        "Horn Venom",
        "Horn Shot",
        "Tomato Fang",
        "Tomato Tackle",
        "Tomato Ketchup",
        "Stone Breath",
        "Fluster",
        "Scurry",
        "Peck",
        "Scatter",
        "Wake-Up Call",
        "Choco Cure",
        "Choco Esuna",
        "Choco Flame",
        "Choco Meteor",
        "Choco Beak",
        "Choco Recharge",
        "Choco Guard",
        "Choco Barrier",
        "Unction",
        "Merge",
        "Acid",
        "Simper",
        "Menace",
        "Self-destruct",
        "Flame Attack",
        "Spark",
        "Miasma",
        "Drain Touch",
        "Flash",
        "Sleep Touch",
        "Silence Touch",
        "Wake the Dead",
        "Doom",
        "Steal Thoughts",
        "Deep Sleep",
        "Shackle",
        "Vampire",
        "Supersonic Wave",
        "Death Dive",
        "Gnaw",
        "Roulette",
        "Glare",
        "Demonic Gaze",
        "Binding Circle",
        "Dread",
        "Bewitching Glance",
        "Knife",
        "Karma",
        "Butcher's Knife",
        "Voodoo",
        "Stalk",
        "Quake",
        "Bone Shatter",
        "Brute Strength",
        "Sunder Earth",
        "Helmsplitter",
        "Rend Shield",
        "Rend Defense",
        "Hell Assault",
        "Pester",
        "Punish",
        "Reward",
        "Fireball",
        "Ice Orb",
        "Lightning",
        "Expose Weakness",
        "Mighty Guard",
        "Dragon Force",
        "Mesmerize",
        "Sleet",
        "Shockbolt",
        "Rock",
        "Scissors",
        "-",
        "-",
        "-",
        "Draw In",
        "Stun Crush",
        "Gravity Flux",
        "Seed",
        "Nectar Volley",
        "Vine Lash",
        "Telega",
        "Repel",
        "Shining Darkness",
        "Grand Cross",
        "Consumption",
        "White Hole",
        "Syphonja",
        "Dispelja",
        "Apocalypse",
        "Gigadust",
        "Catastrophe",
        "Dark",
        "Darkra",
        "Darkga",
        "Invert",
        "Hellfire",
        "Frostwave",
        "Soul Purge",
        "Gaia's Wrath",
        "Tsunami",
        "Judgment Bolt",
        "Blight",
        "Condemnation",
        "Tornado",
        "Big Bang",
        "Meteor",
        "Ultima",
        "Final Eclipse",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "Attack",
        "Blinding Cloud",
        "Soporific Cloud",
        "Bewildering Cloud",
        "Gravija",
        "Fortify",
        "Peck",
        "Devour",
        "Territorial Marking",
        "Piston Drop",
        "Primary Weapon",
        "Secondary Weapon",
        "Beguile",
        "Punishing Ray",
        "Charge Ray",
        "Restoration Ray",
        "Sanctify",
        "Rewind",
        "-",
        "-",
        "-",
        "-",
        "-",
        "Critical: Quicken",
        "Critical: Haste",
        "Critical: Berserk",
        "Sticky Fingers",
        "Reflex",
        "Archer's Bane",
        "Strike Back",
        "Counter",
        "Return Fire",
        "Bonecrusher",
        "Magick Counter",
        "Dragonheart",
        "MP Shield",
        "Regenerate",
        "Absorb MP",
        "Blur",
        "Absorb Damage",
        "Evade Magick",
        "Critical: Evasion↑",
        "Blink Counter",
        "Gil Snapper",
        "Critical: Vanish",
        "Replenish MP",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "Attack↑",
        "Defense↑",
        "Magick↑",
        "Resistance↑",
        "Turbo MP",
        "Geomancy",
        "Pierce",
        "Monkey Grip",
        "Doublehand",
        "Dual Wield",
        "Safeguard",
        "Halve MP",
        "Immunity",
        "Learn",
        "Concentration",
        "Reveal",
        "Shieldbearer",
        "Death Strike",
        "Unscarred",
        "Item Lore",
        "Spellbound",
        "Charged Attacks",
        "Avoid Traps",
        "Blood Price",
        "Smasher",
        "Vigilance",
        "Pugilist",
        "Archmage",
        "Destroyer",
        "Lifespring",
        "Elusion",
        "Impervious",
        "Ribbon-bearer",
        "Tank",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
    };

    //public static List<String> nameWithIndex = IntStream.range(0, App.abilityNames.size()).mapToObj(i -> String.format("%X: %s", i, App.abilityNames.get(i))).toList();
}
